# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the Preprocess image
        run: docker build ./boston_housing/preprocess_data --tag cliffvj/boston_pipeline_preprocessing
      - name: Push the Preprocess image
        run: docker push cliffvj/boston_pipeline_preprocessing
      - name: Build the Train image
        run: docker build ./boston_housing/train --tag cliffvj/boston_pipeline_train
      - name: Push the Train image
        run: docker push cliffvj/boston_pipeline_train
      - name: Build the Test image
        run: docker build ./boston_housing/test --tag cliffvj/boston_pipeline_test
      - name: Push the Test image
        run: docker push cliffvj/boston_pipeline_test
      - name: Build the Deploy image
        run: docker build ./boston_housing/deploy_model --tag cliffvj/boston_pipeline_deploy_model
      - name: Push the Deploy image
        run: docker push cliffvj/boston_pipeline_deploy_model
